### ISSUE TITLE
Fatal error occurred on app startup using new MatrixSdkDatabase with some accounts

### ISSUE THREAD

**Issue by Airyzz** [commetchat/commet#178]
Fatal Error Occurred!
DatabaseException(Row too big to fit into CursorWindow requiredPos=46, totalRows=47) sql 'SELECT * FROM box_room_account_data' args []

<details open>
<summary>Device Information</summary>
<br>

**Device**
Platform: `android`
Version: `development`
Git Hash: `unknown`
Detail: `default`

**System Info**

Product: `barbet`
</details>

<details open>
<summary>Stack Trace</summary>
<br>

```
#0      wrapDatabaseException (package:sqflite/src/exception_impl.dart:11)
<asynchronous suspension>
#1      SqfliteDatabaseMixin.txnRawQuery.<anonymous closure> (package:sqflite_common/src/database_mixin.dart:575)
<asynchronous suspension>
#2      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33)
<asynchronous suspension>
#3      SqfliteDatabaseMixin.txnSynchronized (package:sqflite_common/src/database_mixin.dart:506)
<asynchronous suspension>
#4      Box.getAllValues (package:matrix/src/database/sqflite_box.dart:145)
<asynchronous suspension>
#5      MatrixSdkDatabase.getRoomList.<anonymous closure> (package:matrix/src/database/matrix_sdk_database.dart:579)
<asynchronous suspension>
#6      Client.init (package:matrix/src/client.dart:1578)
<asynchronous suspension>
#7      MatrixClient.init.<anonymous closure> (package:commet/client/matrix/matrix_client.dart:189)
<asynchronous suspension>
#8      MatrixClient.init (package:commet/client/matrix/matrix_client.dart:188)
<asynchronous suspension>
#9      MatrixClient.loadFromDB.<anonymous closure>.<anonymous closure> (package:commet/client/matrix/matrix_client.dart:155)
<asynchronous suspension>
#10     Future.wait.<anonymous closure> (dart:async/future.dart:525)
<asynchronous suspension>
#11     MatrixClient.loadFromDB.<anonymous closure> (package:commet/client/matrix/matrix_client.dart:164)
<asynchronous suspension>
#12     MatrixClient.loadFromDB (package:commet/client/matrix/matrix_client.dart:141)
<asynchronous suspension>
#13     Future.wait.<anonymous closure> (dart:async/future.dart:525)
<asynchronous suspension>
#14     ClientManager.init (package:commet/client/client_manager.dart:75)
<asynchronous suspension>
#15     Future.wait.<anonymous closure> (dart:async/future.dart:525)
<asynchronous suspension>
#16     initNecessary (package:commet/main.dart:135)
<asynchronous suspension>
#17     appMain (package:commet/main.dart:110)
<asynchronous suspension>

```

</details>

**Comment by Airyzz** [comment]
Looks like it isnt actually just multi-account that is causing problems, but actually is an issue specific to one of my accounts

**Comment by Airyzz** [comment]
Opened an upstream issue: https://github.com/famedly/matrix-dart-sdk/issues/1642
