### ISSUE TITLE
Null check operator used on a null value

### ISSUE THREAD

**Issue by Airyzz** [commetchat/commet#245]
```
#0      State.setState (package:flutter/src/widgets/framework.dart:1223)
#1      _PeerListState.onMembersListUpdated (package:commet/ui/molecules/user_list.dart:30)
#2      _rootRunUnary (dart:async/zone.dart:1407)
#3      _CustomZone.runUnary (dart:async/zone.dart:1308)
#4      _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#5      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#6      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271)
#7      _SyncBroadcastStreamController._sendData.<anonymous closure> (dart:async/broadcast_stream_controller.dart:385)
#8      _BroadcastStreamController._forEachListener (dart:async/broadcast_stream_controller.dart:322)
#9      _SyncBroadcastStreamController._sendData (dart:async/broadcast_stream_controller.dart:384)
#10     _BroadcastStreamController.add (dart:async/broadcast_stream_controller.dart:244)
#11     NotifyingList._onAnyUpdate (package:commet/utils/notifying_list.dart:71)
#12     NotifyingList.addAll (package:commet/utils/notifying_list.dart:109)
#13     MatrixRoom.onRoomStateUpdated (package:commet/client/matrix/matrix_room.dart:214)
#14     _rootRunUnary (dart:async/zone.dart:1415)
#15     _CustomZone.runUnary (dart:async/zone.dart:1308)
#16     _CustomZone.runUnaryGuarded (dart:async/zone.dart:1217)
#17     _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339)
#18     _DelayedData.perform (dart:async/stream_impl.dart:515)
#19     _PendingEvents.handleNext (dart:async/stream_impl.dart:620)
#20     _PendingEvents.schedule.<anonymous closure> (dart:async/stream_impl.dart:591)
#21     _microtaskLoop (dart:async/schedule_microtask.dart:40)
```

**Comment by Airyzz** [comment]
This code no longer exists
